parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        # configure these for your database server
        connections:
            default:
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                # With Symfony 3.3, remove the `resolve:` prefix
                url: '%env(resolve:DATABASE_URL_READ)%'
            write:
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                # With Symfony 3.3, remove the `resolve:` prefix
                url: '%env(resolve:DATABASE_URL_WRITE)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore
            write:
                connection: write
                naming_strategy: doctrine.orm.naming_strategy.underscore



