App\Kernel\Domain\Model\StoredEvent:
  type: entity
  table: event
  repositoryClass: App\Kernel\Infrastructure\Domain\Event\DoctrineEventStore
  id:
    eventId:
      type: integer
      generator:
        strategy: AUTO
  fields:
    eventBody:
      type: text
    typeName:
      type: string
      length: 255
    occurredOn:
      type: datetime
    executed:
      type: boolean
    executedDate:
      type: datetime
      nullable: true