App\Post\Domain\Model\Post:
    type: entity
    table: null
    repositoryClass: App\Post\Infrastructure\Domain\Model\DoctrinePostRepository
    id:
        postId:
          column: id
          type: PostId
    fields:
        dateCreation:
            type: datetime
        date:
            type: datetime
        title:
            type: string
            length: '150'
        text:
            type: text
            nullable: true
    oneToMany:
        comments:
            targetEntity: App\Post\Domain\Model\PostComment
            cascade: ["persist", "remove"]
            orphanRemoval: true
            fetch: EXTRA_LAZY
            mappedBy: post
    lifecycleCallbacks: {  }